apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/jenkins-oscar/terraform-sample:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/jenkins-oscar/terraform-sample:{{.VERSION}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: terraform-sample
        chartPath: charts/terraform-sample
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/jenkins-oscar/terraform-sample'
          image.tag: '{{.VERSION}}'
